### PR TITLE
Bump GHC 9.4 to minor version 9.4.6

### PR DESCRIPTION
**Pull request by jhrcek**

### CODE REVIEW

**Review by develop7 — APPROVED** [review]
LGTM

**Comment by jhrcek** [comment]
@AlistairB (I realize you no longer want to be maintainer) or @develop7 could you please merge? I can then open a PR in official images repo..

**Comment by AlistairB** [comment]
Thanks @jhrcek ! Are you interested in being added as maintainer as well?

**Comment by jhrcek** [comment]
Not really. I know enough to follow readme/update hash, but not enough to be able to contribute more meaningfully :smile:

**Comment by AlistairB** [comment]
Hehe, that is enough! But no problem to to you.

**Pull request merged**
