### PR TITLE
GHC 9.6.6

### PR DESCRIPTION
**Pull request by jhrcek**
Hello @develop7 
could you take a look, please?

### CODE REVIEW

**Review by develop7 — APPROVED** [review]
LGTM, thanks!

**Comment by jhrcek** [comment]
Oops, seems like this won't be accepted in official images repo anymore:
https://github.com/docker-library/official-images/pull/17175

```
Invalid 'FROM' + 'Architectures' combinations detected:

 - haskell:9.0.2-buster (FROM buildpack-deps:buster) -- completely unsupported base!
 - haskell:9.0.2-slim-buster (FROM debian:buster-slim) -- completely unsupported base!
 - haskell:9.10.1-buster (FROM buildpack-deps:buster) -- completely unsupported base!
 - haskell:9.10.1-slim-buster (FROM debian:buster-slim) -- completely unsupported base!
 - haskell:9.2.8-buster (FROM buildpack-deps:buster) -- completely unsupported base!
 - haskell:9.2.8-slim-buster (FROM debian:buster-slim) -- completely unsupported base!
 - haskell:9.4.8-buster (FROM buildpack-deps:buster) -- completely unsupported base!
 - haskell:9.4.8-slim-buster (FROM debian:buster-slim) -- completely unsupported base!
 - haskell:9.6.6-buster (FROM buildpack-deps:buster) -- completely unsupported base!
 - haskell:9.6.6-slim-buster (FROM debian:buster-slim) -- completely unsupported base!
 - haskell:9.8.2-buster (FROM buildpack-deps:buster) -- completely unsupported base!
 - haskell:9.8.2-slim-buster (FROM debian:buster-slim) -- completely unsupported base!
```

Seems like buster LTS ended few weekes ago: 
https://wiki.debian.org/DebianReleases
@develop7 @AlistairB any idea how much effort would it be to switch over to debian 11?

**Comment by develop7** [comment]
Ah shoot

**Comment by develop7** [comment]
@jhrcek 9.10 in #134 seems to be fine, but we don't have 9.6.6 builds for aarch64-deb11, hence I have to try deb10 on bullseye

**Pull request merged**
