### PR TITLE
Bump GHC 9.2 to 9.2.6

### PR DESCRIPTION
**Pull request by tarleb**

### CODE REVIEW

**Review by AlistairB — APPROVED** [review]
Perfect, thanks!

Next step is to update the [official images repo](https://github.com/docker-library/official-images/blob/master/library/haskell) if you want to give that a go?

**Comment by tarleb** [comment]
On it.

**Comment by tarleb** [comment]
For the record: docker-library/official-images#14091

**Comment by AlistairB** [comment]
Awesome, thanks!

**Pull request merged**
