### PR TITLE
Add .dockerignore file

### PR DESCRIPTION
**Pull request by tarleb**
Reduces the build context from megabytes to kilobytes.

### CODE REVIEW

**Comment by tarleb** [comment]
I don't think this matters here, as the build context is small anyway, so the speedup is minimal.

**Review by AlistairB — COMMENTED** [review]
Cool idea! I think actually this can just be `*` as the whole file. I think you only need files / directories in the context if they are being added into the image somehow. With just `*` it still seems to work fine.

**Comment by tarleb** [comment]
Ah, true! I'm so use to needing subfolders that I didn't think of that. :man_facepalming:

**Review by AlistairB — APPROVED** [review]
Thanks

**Pull request merged**
