### PR TITLE
feat: introduce bullseye builds for 9.6.6

### PR DESCRIPTION
**Pull request by develop7**
Falls back to  buster bindist on aarch64,

### CODE REVIEW

**Comment by Totto16** [comment]
Is there a reason why this is still a draft? 
Is there help needed or can I help in any way possible. (I know my way around docker images and am not new to the topic)

I am asking this, since I am using the [stackage LTS snapshots](https://www.stackage.org/snapshots), and they updated the LTS over a month ago to Haskell 9.6.6: [see here](https://www.stackage.org/lts-22.28)

A big thanks to you, since you seem to maintain this alone and for a long time ❤️

**Comment by develop7** [comment]
> Is there a reason why this is still a draft? 

I've tried to produce deb11 images for aarch64 with deb10 bindists, to no avail

**Comment by Totto16** [comment]
> > Is there a reason why this is still a draft?
> 
> I've tried to produce deb11 images for aarch64 with deb10 bindists, to no avail

Oh I see, there is no release ghc-9.6.6-aarch64-deb11-linux.tar.xz
😓

**Comment by develop7** [comment]
Superseded by #137

**Pull request closed without merging**
