### PR TITLE
Add GHC 9.6

### PR DESCRIPTION
**Pull request by develop7**
Introduces GHC 9.6

### CODE REVIEW

**Comment by AlistairB** [comment]
Thanks, does ghc 9.6 require cabal 3.10? Cabal 3.10 was blocked on https://github.com/haskell/cabal/issues/8849 . Also don't suppose you would interested in being added as maintainer of these images? :upside_down_face: We have no particularly active maintainers atm and I am stepping away from the project (no pressure).

**Comment by develop7** [comment]
> does ghc 9.6 require cabal 3.10?

It does print a warning, yes, but otherwise it gets built successfully (haven't run the test suite though; should do them probably)

**Comment by develop7** [comment]
> Also don't suppose you would interested in being added as maintainer of these images? :upside_down_face: We have no particularly active maintainers atm and I am stepping away from the project (no pressure). 

Not at all, go for it.

**Comment by AlistairB** [comment]
Cool, I have added your as a maintainer. My personal inclination would be to wait for [cabal 3.10.2.0](https://github.com/haskell/cabal/issues/9008) which will hopefully fix the aarch64 release issue. However, it might be fine to use 3.8 despite the warning. Feel free to merge and do a [release](https://github.com/haskell/docker-haskell#2-release-new-versions). I can approve the official images PR.

**Comment by develop7** [comment]
squash-merged and released (docker-library/official-images#15222)

> However, it might be fine to use 3.8 despite the warning.

I was thinking to keep 3.8 in `aarch64` only, but then decided not to, for the sake of consistency

**Comment by tarleb** [comment]
> We have no particularly active maintainers

I'm very sorry for disappearing. I'm back now and trying to pick things up again. Very happy to see we're growing :wave:

**Comment by AlistairB** [comment]
No worries! Yes lots of good activity!

**Pull request merged**
